import mysql.connector as conn

connect = conn.connect(host = "localhost",user = "root", password = "root")
print(connect)
cursor = connect.cursor()
cursor.execute("use sqlclass")
# cursor.execute("create table details(name char(10),age int(4))")
# cursor.execute("describe details")
cursor.execute('insert into details values("sachin",23)')
cursor.execute('insert into details values("sachin",23)')
cursor.execute('insert into details values("sachin",23)')
cursor.execute('insert into details values("sachin",23)')
cursor.execute('insert into details values("sachin",23)')
cursor.execute('insert into details values("sachin",23)')
cursor.execute('insert into details values("sachin",23)')
cursor.execute('insert into details values("sachin",23)')
connect.commit()
cursor.execute('select * from details')
print(cursor.fetchall())
connect.close()
